################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Support"
footer_menu_right = "Contact"
footer_content = ""


################################### Thai language #####################################
[th]
languageName = "TH"
languageCode = "th-TH"
contentDir = "content/thai"
weight = 2
########### footer content ##########
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
footer_content = ""

