################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Support"
footer_menu_right = "Contact"
footer_content = ""


################################### Thai language #####################################
[th]
languageName = "TH"
languageCode = "th-THA"
contentDir = "content/th"
weight = 2
########### footer content ##########
footer_menu_left = "บริษัท"
footer_menu_middle = "สนับสนุน"
footer_menu_right = "ติดต่อ"
footer_content = ""